"""initial schema

Revision ID: 8796dd2cac3b
Revises: 
Create Date: 2026-05-28 12:15:16.782567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8796dd2cac3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_faculties_id'), 'faculties', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=True),
    sa.Column('system_motto', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('active_academic_year', sa.Integer(), nullable=False),
    sa.Column('submission_deadline', sa.Date(), nullable=False),
    sa.Column('is_accepting_applications', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('other_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'sgo_admin', 'staff', 'reviewer', name='userrole'), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('grant_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grant_type', sa.Enum('research', 'innovation', name='granttype'), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('max_budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', name='grantcallstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grant_calls_id'), 'grant_calls', ['id'], unique=False)
    op.create_table('otp_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_tokens_id'), 'otp_tokens', ['id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_no', sa.String(length=50), nullable=False),
    sa.Column('grant_type', sa.Enum('research', 'innovation', name='granttype'), nullable=False),
    sa.Column('pi_first_name', sa.String(length=100), nullable=False),
    sa.Column('pi_last_name', sa.String(length=100), nullable=False),
    sa.Column('pi_qualification', sa.String(length=100), nullable=False),
    sa.Column('pi_gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('pi_designation', sa.String(length=100), nullable=False),
    sa.Column('pi_faculty_id', sa.Integer(), nullable=False),
    sa.Column('pi_department', sa.String(length=200), nullable=False),
    sa.Column('pi_research_specialization', sa.String(length=200), nullable=False),
    sa.Column('pi_email', sa.String(length=255), nullable=False),
    sa.Column('pi_phone', sa.String(length=20), nullable=False),
    sa.Column('research_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('project_summary', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('proposed_solution', sa.Text(), nullable=False),
    sa.Column('relevance', sa.Text(), nullable=False),
    sa.Column('innovativeness', sa.Text(), nullable=False),
    sa.Column('main_objective', sa.Text(), nullable=False),
    sa.Column('specific_objectives', sa.Text(), nullable=False),
    sa.Column('methods_description', sa.Text(), nullable=False),
    sa.Column('outcomes', sa.Text(), nullable=False),
    sa.Column('dissemination_plan', sa.Text(), nullable=False),
    sa.Column('policy_impact', sa.Text(), nullable=False),
    sa.Column('scalability', sa.Text(), nullable=False),
    sa.Column('sustainability', sa.Text(), nullable=False),
    sa.Column('gender_considerations', sa.Text(), nullable=False),
    sa.Column('ethical_impact', sa.Text(), nullable=False),
    sa.Column('capacity_building', sa.Text(), nullable=False),
    sa.Column('conflict_of_interest', sa.Text(), nullable=False),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'missing_attachments', 'submitted', 'scheduled_for_review', 'reviewed', 'approved', 'rejected', 'awarded', name='proposalstatus'), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_decision', sa.String(length=50), nullable=True),
    sa.Column('admin_decision_note', sa.Text(), nullable=True),
    sa.Column('admin_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pi_faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_protocol_no'), 'proposals', ['protocol_no'], unique=True)
    op.create_table('reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('research_discipline', sa.String(length=200), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_reviewers_id'), 'reviewers', ['id'], unique=False)
    op.create_table('project_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_team_members_id'), 'project_team_members', ['id'], unique=False)
    op.create_table('proposal_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.Enum('gantt_chart', 'budget', 'national_id', 'confirmation_letter', 'cvs', 'consent_forms', 'research_instruments', 'faculty_support', 'full_proposal', name='attachmenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('cloudinary_url', sa.Text(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_attachments_id'), 'proposal_attachments', ['id'], unique=False)
    op.create_table('proposal_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=100), nullable=True),
    sa.Column('new_status', sa.String(length=100), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_status_history_id'), 'proposal_status_history', ['id'], unique=False)
    op.create_table('review_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_assignments_id'), 'review_assignments', ['id'], unique=False)
    op.create_table('reviewer_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Enum('approve', 'minor_revisions', 'major_revisions', 'reject', name='reviewrecommendation'), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('report_file_url', sa.Text(), nullable=True),
    sa.Column('report_file_public_id', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['review_assignments.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    op.create_index(op.f('ix_reviewer_reports_id'), 'reviewer_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewer_reports_id'), table_name='reviewer_reports')
    op.drop_table('reviewer_reports')
    op.drop_index(op.f('ix_review_assignments_id'), table_name='review_assignments')
    op.drop_table('review_assignments')
    op.drop_index(op.f('ix_proposal_status_history_id'), table_name='proposal_status_history')
    op.drop_table('proposal_status_history')
    op.drop_index(op.f('ix_proposal_attachments_id'), table_name='proposal_attachments')
    op.drop_table('proposal_attachments')
    op.drop_index(op.f('ix_project_team_members_id'), table_name='project_team_members')
    op.drop_table('project_team_members')
    op.drop_index(op.f('ix_reviewers_id'), table_name='reviewers')
    op.drop_table('reviewers')
    op.drop_index(op.f('ix_proposals_protocol_no'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_otp_tokens_id'), table_name='otp_tokens')
    op.drop_table('otp_tokens')
    op.drop_index(op.f('ix_grant_calls_id'), table_name='grant_calls')
    op.drop_table('grant_calls')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_faculties_id'), table_name='faculties')
    op.drop_table('faculties')
    # ### end Alembic commands ###
